CREATE DATABASE CASOSCOVID;
USE CASOSCOVID;

CREATE TABLE ADMINISTRADORES(IdAdministrador INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(40),
Apellido VARCHAR(40),
CorreoElectronico VARCHAR(40),
Contraseña VARCHAR(40)
);
CREATE TABLE USUARIOS(IdUsuario INT NOT NULL PRIMARY KEY,
Nombre VARCHAR(40),
Apellido VARCHAR(40),
CorreoElectronico VARCHAR(40),
Contraseña VARCHAR(40)
);
CREATE TABLE REPORTES(IdReporte INT NOT NULL PRIMARY KEY,
NombreDeUsuario VARCHAR(40),
Municipio VARCHAR(40),
Ciudad VARCHAR(40),
Direccion VARCHAR(40),
FechaDeReporte DATE,
STATUS VARCHAR(40),
IdUsuario int,
FOREIGN KEY(IdUsuario)REFERENCES USUARIOS(IdUsuario)
);